markdown: redcarpet
pygments: true
exclude: ['Gemfile', 'Gemfile.lock', 'Makefile']
title: Athletes By Design
url: http://abdcycling.github.io
permalink: /news/:title
paginate: 5
paginate_path: "news/page:num"
author:
    name: Athletes By Design
    email: abdcycling@gmail.com
    github: abdcycling
    twitter: abdcycling
version: 1.0.0
github:
    repo: github.com/abdcycling/abdcycling.github.io
gems:
- jekyll-sitemap
- jekyll-redirect-from
