exclude: [
  'Gemfile',
  'Gemfile.lock',
  'Gruntfile.js',
  'node_modules',
  'package.json',
  'README.md',
]
title: Athletes By Design
url: https://www.abdcycling.com
enforce_ssl: www.abdcycling.com
permalink: /news/:title
paginate: 5
paginate_path: "news/page:num"
author:
  name: Athletes By Design
  email: abdcycling@gmail.com
  github: abdcycling
  twitter: 'http://www.twitter.com/abdcycling'
  facebook: 'http://www.facebook.com/abdcycling'
  googleplus: 'https://plus.google.com/b/112886249020749336787?rel=author'
  youtube: 'http://www.youtube.com/abdcycling'
version: 2019.02.09
github:
  repo: github.com/abdcycling/abdcycling.github.io
gems:
- jekyll-sitemap
- jekyll-paginate
